### ISSUE TITLE
Current version of the command line tool is broken

### ISSUE THREAD

**Issue by mailund** [mailund/gwf#111]
If I check out master and run gwf I get the following error:

```
$ gwf --help
Traceback (most recent call last):
  File "/Users/mailund/anaconda/bin/gwf", line 9, in <module>
    load_entry_point('gwf', 'console_scripts', 'gwf')()
  File "/Users/mailund/anaconda/lib/python2.7/site-packages/setuptools-23.0.0-py2.7.egg/pkg_resources/__init__.py", line 542, in load_entry_point
  File "/Users/mailund/anaconda/lib/python2.7/site-packages/setuptools-23.0.0-py2.7.egg/pkg_resources/__init__.py", line 2569, in load_entry_point
  File "/Users/mailund/anaconda/lib/python2.7/site-packages/setuptools-23.0.0-py2.7.egg/pkg_resources/__init__.py", line 2229, in load
  File "/Users/mailund/anaconda/lib/python2.7/site-packages/setuptools-23.0.0-py2.7.egg/pkg_resources/__init__.py", line 2235, in resolve
  File "/Users/mailund/Projects/gwf/gwf/__init__.py", line 3, in <module>
    from gwf.core import PreparedWorkflow, Target, Workflow
  File "/Users/mailund/Projects/gwf/gwf/core.py", line 12, in <module>
    from .utils import (cache, dfs, get_file_timestamp, import_object,
  File "/Users/mailund/Projects/gwf/gwf/utils.py", line 87
SyntaxError: Non-ASCII character '\xc2' in file /Users/mailund/Projects/gwf/gwf/utils.py on line 87, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
```

**Comment by mailund** [comment]
this *might* have been a conda issue on my machine, though...
