### ISSUE TITLE
IsADirectoryError caused by old, user-specific state directory

### ISSUE THREAD

**Issue by dansondergaard** [mailund/gwf#128]
Reported by @micknudsen.

```
(gwf_test) [michaelk@fe1 gwf_tests]$ ll
total 0
-rw-r--r-- 1 michaelk michaelk 140 Jan 23 11:10 workflow.py

(gwf_test) [michaelk@fe1 gwf_tests]$ gwf workers
Traceback (most recent call last):
 File "/home/michaelk/anaconda/envs/gwf_test/bin/gwf", line 6, in <module>
   sys.exit(gwf.cli.main())
 File "/home/michaelk/anaconda/envs/gwf_test/lib/python3.6/site-packages/gwf-1.0b1-py3.6.egg/gwf/cli.py", line 215, in main
 File "/home/michaelk/anaconda/envs/gwf_test/lib/python3.6/site-packages/gwf-1.0b1-py3.6.egg/gwf/cli.py", line 113, in run
 File "/home/michaelk/anaconda/envs/gwf_test/lib/python3.6/site-packages/ConfigArgParse-0.11.0-py3.6.egg/configargparse.py", line 402, in parse_args
 File "/home/michaelk/anaconda/envs/gwf_test/lib/python3.6/site-packages/ConfigArgParse-0.11.0-py3.6.egg/configargparse.py", line 496, in parse_known_args
 File "/home/michaelk/anaconda/envs/gwf_test/lib/python3.6/site-packages/ConfigArgParse-0.11.0-py3.6.egg/configargparse.py", line 716, in _open_config_files
 File "/home/michaelk/anaconda/envs/gwf_test/lib/python3.6/site-packages/ConfigArgParse-0.11.0-py3.6.egg/configargparse.py", line 717, in <listcomp>
IsADirectoryError: [Errno 21] Is a directory: '/home/michaelk/.gwf’

(gwf_test) [michaelk@fe1 gwf_tests]$ gwf
Traceback (most recent call last):
 File "/home/michaelk/anaconda/envs/gwf_test/bin/gwf", line 6, in <module>
   sys.exit(gwf.cli.main())
 File "/home/michaelk/anaconda/envs/gwf_test/lib/python3.6/site-packages/gwf-1.0b1-py3.6.egg/gwf/cli.py", line 215, in main
 File "/home/michaelk/anaconda/envs/gwf_test/lib/python3.6/site-packages/gwf-1.0b1-py3.6.egg/gwf/cli.py", line 113, in run
 File "/home/michaelk/anaconda/envs/gwf_test/lib/python3.6/site-packages/ConfigArgParse-0.11.0-py3.6.egg/configargparse.py", line 402, in parse_args
 File "/home/michaelk/anaconda/envs/gwf_test/lib/python3.6/site-packages/ConfigArgParse-0.11.0-py3.6.egg/configargparse.py", line 496, in parse_known_args
 File "/home/michaelk/anaconda/envs/gwf_test/lib/python3.6/site-packages/ConfigArgParse-0.11.0-py3.6.egg/configargparse.py", line 716, in _open_config_files
 File "/home/michaelk/anaconda/envs/gwf_test/lib/python3.6/site-packages/ConfigArgParse-0.11.0-py3.6.egg/configargparse.py", line 717, in <listcomp>
IsADirectoryError: [Errno 21] Is a directory: '/home/michaelk/.gwf'
```

**Comment by micknudsen** [comment]
Deleting ~/.gwf folder allows me to start gwf workers. However, `gwf run` subsequently fails due to a local .gwf folder:

> (gwf_test) [michaelk@fe1 gwf_tests]$ gwf run
> Traceback (most recent call last):
>   File "/home/michaelk/anaconda/envs/gwf_test/bin/gwf", line 6, in <module>
>     sys.exit(gwf.cli.main())
>   File "/home/michaelk/anaconda/envs/gwf_test/lib/python3.6/site-packages/gwf-1.0b1-py3.6.egg/gwf/cli.py", line 215, in main
>   File "/home/michaelk/anaconda/envs/gwf_test/lib/python3.6/site-packages/gwf-1.0b1-py3.6.egg/gwf/cli.py", line 113, in run
>   File "/home/michaelk/anaconda/envs/gwf_test/lib/python3.6/site-packages/ConfigArgParse-0.11.0-py3.6.egg/configargparse.py", line 402, in parse_args
>   File "/home/michaelk/anaconda/envs/gwf_test/lib/python3.6/site-packages/ConfigArgParse-0.11.0-py3.6.egg/configargparse.py", line 496, in parse_known_args
>   File "/home/michaelk/anaconda/envs/gwf_test/lib/python3.6/site-packages/ConfigArgParse-0.11.0-py3.6.egg/configargparse.py", line 716, in _open_config_files
>   File "/home/michaelk/anaconda/envs/gwf_test/lib/python3.6/site-packages/ConfigArgParse-0.11.0-py3.6.egg/configargparse.py", line 717, in <listcomp>
> IsADirectoryError: [Errno 21] Is a directory: '.gwf'

**Comment by dansondergaard** [comment]
Argh. The configuration file should probably be called `.gwf.conf` instead, to avoid any clashes with state directories and old configuration files. Thanks!
