### ISSUE TITLE
Missing defaults crass...

### ISSUE THREAD

**Issue by mailund** [mailund/gwf#131]
If I run a complete vanilla `gwf status` in the example dir, I get this error: 

```sh
$ gwf status                                                                
Traceback (most recent call last):
  File "/Users/mailund/anaconda/envs/Py35/bin/gwf", line 11, in <module>
    load_entry_point('gwf', 'console_scripts', 'gwf')()
  File "/Users/mailund/Projects/gwf/gwf/cli.py", line 215, in main
    app.run(sys.argv[1:])
  File "/Users/mailund/Projects/gwf/gwf/cli.py", line 162, in run
    workflow.defaults,
AttributeError: module 'gwf' has no attribute 'defaults'
```

**Comment by mailund** [comment]
ok, that seems to be because I didn't call my workflow `gwf`. 

Changing that doesn't make it work, of course, but the error is different now :)
