### ISSUE TITLE
If the user configuration file is missing, gwf crashes

### ISSUE THREAD

**Issue by mailund** [mailund/gwf#132]
This:

```sh
(Py35) ➜  minimal-workflow (master) gwf config -u backend local                                        ✭ ✱
Traceback (most recent call last):
  File "/Users/mailund/anaconda/envs/Py35/bin/gwf", line 11, in <module>
    load_entry_point('gwf', 'console_scripts', 'gwf')()
  File "/Users/mailund/Projects/gwf/gwf/cli.py", line 215, in main
    app.run(sys.argv[1:])
  File "/Users/mailund/Projects/gwf/gwf/cli.py", line 191, in run
    handler()
  File "/Users/mailund/Projects/gwf/gwf/plugins/config.py", line 77, in on_run
    with open(config_path, 'w') as fileobj:
FileNotFoundError: [Errno 2] No such file or directory: '~/.gwf.conf'
```

We should probably just create it, if it is missing.

**Comment by dansondergaard** [comment]
I think this mostly a problem with the non-absolute path. It should be expanded.
